### ISSUE TITLE
SID optimization?

### ISSUE THREAD

**Issue by PatrickvL** [cadaver/oldschoolengine2-emscripten#3]
In SID.c, `if (adsrCounter == adsrTarget)` starts each switch case, so could be moved outside to avoid the switch in most iterations (unless measurements show the opposite, and the compiler optimiser doesn't handle this already).

Terminology-wise, what this repository calls "channels" are called "voices" in original SID documentation (and similarly, channel "volume" is called "envelope").

**Comment by cadaver** [comment]
Thanks for your investigation! The way the code behaves now, it already needs to know the ADSR state to know how many cycles to emulate ahead, until it reaches the ADSR target counter value, so the compiler might reuse that info for the switch-case, and structure the code differently. Nevertheless it's a good idea to not repeat statements.
